name: Pipravi podatke

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Poskrbi, da bo uporabljena verzija, združljiva s TensorFlow 2.10.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run fetch_data.py
      run: |
        python notebooks/Naloga01-IIS/fetch_data.py
        
    - name: Run pre_process.py
      run: |
        python notebooks/Naloga01-IIS/pre_process.py
        
    - name: Run GreatExpectations
      run: |
        pip install great_expectations
        python notebooks/Naloga01-IIS/greatExp.py

    - name: Run Evidently
      run: |
        pip install evidently
        python notebooks/Naloga01-IIS/evidently_script.py
